
export const PURCHASE_POLICIES = 'PURCHASE_POLICIES';
export const PURCHASE_POLICIES_START = 'PURCHASE_POLICIES_START';
export const PURCHASE_POLICIES_SUCCESS = 'PURCHASE_POLICIES_SUCCESS';
export const PURCHASE_POLICIES_FAIL = 'PURCHASE_POLICIES_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';
export const CUSTOMER_SIGNUP_START = 'CUSTOMER_SIGNUP_START';
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL';
export const CUSTOMER_SIGNUP_INIT = 'CUSTOMER_SIGNUP_INIT';

export const FETCH_CUSTOMER_POLICIES = 'FETCH_CUSTOMER_POLICIES';
export const FETCH_CUSTOMER_POLICIES_START = 'FETCH_CUSTOMER_POLICIES_START';
export const FETCH_CUSTOMER_POLICIES_SUCCESS = 'FETCH_CUSTOMER_POLICIES_SUCCESS';
export const FETCH_CUSTOMER_POLICIES_FAIL = 'FETCH_CUSTOMER_POLICIES_FAIL';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';